"""
Context Cue

Defines the smallest unit of cognitive assistance generated by
Samsung Anchor.

Every subsystem (identity, object, intent, reminders, navigation)
produces ContextCue objects that can later be prioritized and spoken
to the user.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class CueType(Enum):
    """
    Categories of cognitive cues.
    """

    IDENTITY = "identity"
    OBJECT = "object"
    INTENT = "intent"
    TIME = "time"
    REMINDER = "reminder"
    EPISODIC = "episodic"


@dataclass(frozen=True)
class ContextCue:
    """
    Represents one cognitive cue.

    Parameters
    ----------
    cue_type
        Type of cue.

    text
        Minimal text that restores context.

    priority
        Higher values indicate more important cues.

    confidence
        Confidence score between 0 and 1.
    """

    cue_type: CueType
    text: str
    priority: int = 0
    confidence: float = 1.0