"""
Interaction Actions.

Defines actions generated by the Interaction Layer.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class InteractionActionType(Enum):
    """
    Supported interaction actions.
    """

    SPEAK = "speak"


@dataclass(frozen=True)
class InteractionAction:
    """
    Action emitted by the Interaction Manager.
    """

    type: InteractionActionType
    message: str