"""
Interaction Manager.

Converts cognitive events into user-facing interaction actions.
"""

from __future__ import annotations

from src.cognition.reasoning_models import MemoryRecall
from src.interaction.actions import (
    InteractionAction,
    InteractionActionType,
)
from src.interaction.events import (
    PresenceEvent,
    PresenceEventType,
)


class InteractionManager:
    """
    Handles user-facing interaction decisions.
    """

    def handle_event(
        self,
        event: PresenceEvent,
        recall: MemoryRecall | None = None,
    ) -> InteractionAction | None:
        """
        Convert a cognitive event into a user-facing action.
        """

        if event.type != PresenceEventType.PERSON_ARRIVED:
            return None

        if event.name:
            if event.relationship:
                message = f"Hello. Your {event.relationship.lower()}, {event.name}, is here."
            else:
                message = f"Hello. {event.name} is here."
        else:
            message = "Someone is here."
        
        if recall is not None and not recall.should_greet:
            # The Executive Function decided on cognitive silence.
            print(f"[InteractionManager] Cognitive silence. Suppressing interaction for {event.name}.")
            return None

        # --------------------------------------------------
        # Memory-aware interaction
        # --------------------------------------------------

        if recall is not None:
            if recall.generated_response:
                # Use the rich context-restored cue generated by the ContextRestorationEngine
                message += f" {recall.generated_response}"
            elif recall.recalled_memories:
                # Fallback to simple hardcoded summary if no LLM response exists
                memory = recall.recalled_memories[0]

                if memory.summary:
                    message += f" Here's a gentle reminder: {memory.summary}"

                if memory.commitments:
                    message += (
                        f" By the way, you also planned to "
                        f"{memory.commitments[0]}."
                    )

        return InteractionAction(
            type=InteractionActionType.SPEAK,
            message=message,
        )